<div class="wrap ccf-admin-wrap"><h1>Transacciones</h1>
<form method="get"><input type="hidden" name="page" value="ccf-transactions"><input type="month" name="month_key" value="<?php echo esc_attr( $_GET['month_key'] ?? '' ); ?>"><input type="number" name="user_id" placeholder="Usuario" value="<?php echo esc_attr( $_GET['user_id'] ?? '' ); ?>"><select name="reviewed"><option value="">Revisado?</option><option value="1">Sí</option><option value="0">No</option></select><button class="button">Filtrar</button></form>
<form method="post"><?php wp_nonce_field( 'ccf_save_transaction_action' ); ?><h3>Nueva / edición rápida</h3>
<select name="type"><option>income</option><option>expense</option><option>transfer</option><option>adjustment</option><option>allocation</option></select>
<select name="source_account_id"><option value="">Cuenta origen</option><?php foreach ( $accounts as $a ) : ?><option value="<?php echo esc_attr( $a['id'] ); ?>"><?php echo esc_html( $a['name'] ); ?></option><?php endforeach; ?></select>
<select name="destination_account_id"><option value="">Cuenta destino</option><?php foreach ( $accounts as $a ) : ?><option value="<?php echo esc_attr( $a['id'] ); ?>"><?php echo esc_html( $a['name'] ); ?></option><?php endforeach; ?></select>
<select name="category_id"><option value="">Categoría</option><?php foreach ( $categories as $c ) : ?><option value="<?php echo esc_attr( $c['id'] ); ?>"><?php echo esc_html( $c['name'] ); ?></option><?php endforeach; ?></select>
<input type="date" name="transaction_date" required><input type="number" step="0.01" name="amount" required><input type="text" name="description" placeholder="Descripción"><input type="text" name="quick_note" placeholder="Nota rápida"><textarea name="note_content" placeholder="Comentario ampliado"></textarea><label><input type="checkbox" name="note_pending" value="1">Nota pendiente</label>
<button class="button button-primary" name="ccf_save_transaction" value="1">Guardar transacción</button></form>
<table class="widefat striped"><thead><tr><th>ID</th><th>Fecha</th><th>Tipo</th><th>Importe</th><th>Categoría</th><th>Estado</th><th>Revisado</th></tr></thead><tbody><?php foreach ( $transactions as $t ) : ?><tr><td><?php echo esc_html( $t['id'] ); ?></td><td><?php echo esc_html( $t['transaction_date'] ); ?></td><td><?php echo esc_html( $t['type'] ); ?></td><td><?php echo esc_html( number_format( (float) $t['amount'], 2 ) ); ?></td><td><?php echo esc_html( $t['category_id'] ); ?></td><td><?php echo esc_html( $t['status'] ); ?></td><td><?php echo esc_html( $t['reviewed'] ); ?></td></tr><?php endforeach; ?></tbody></table></div>
